#  Headless service to provide stable network identity to each pod in StatefulSet
apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: expense
spec:
  clusterIP: None  #  This makes it a headless service (important for StatefulSets)
  selector:
    component: mysql        #  Must match pod labels
    project: expense
    tier: db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
#  Regular service for other applications to connect to the MySQL StatefulSet
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    component: mysql        #  Must match pod labels
    project: expense
    tier: db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
#  StatefulSet definition for running MySQL pods with persistent volume
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: expense
spec:
  replicas: 2  #  Two MySQL pods will be created: mysql-0, mysql-1
  selector:
    matchLabels:
      project: expense       #  These must match the pod template labels below
      component: mysql
      tier: db
  serviceName: "mysql-headless"  #  Headless service used by this StatefulSet
  template:
    metadata:
      labels:
        project: expense     #  These labels must match the StatefulSet selector
        component: mysql
        tier: db
    spec:
      containers:
        - name: mysql
          image: darauday0/expense-mysql:v1
          imagePullPolicy: Always
          volumeMounts:
            - name: mysql    #  Must match volumeClaimTemplates name below
              mountPath: /var/lib/mysql  #  Corrected: Added leading slash
  #  Template for dynamic PVC creation per pod
  volumeClaimTemplates:
    - metadata:
        name: mysql  #  Used above in volumeMounts
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "expense-ebs"  #  Must exist in cluster
        resources:
          requests:
            storage: 1Gi  #  Fixed typo: 1G  1Gi
